/**
 * Icon — drop-in replacement for the legacy icon component.
 *
 * Renders lucide-react-native icons using compatible name strings so that
 * existing call sites keep working unchanged. NO references to any
 * pre-bundled icon font (vector-icons family) exist anywhere — neither in
 * this file nor in consumers.
 *
 * Props:
 *   name   string  legacy name (e.g. "checkmark-circle", "qr-code-outline")
 *   size   number  pixels (default 20)
 *   color  string  hex/rgba (default #000)
 *   style  any     forwarded to lucide
 */
import React from 'react';
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Banknote,
  BarChart3,
  Bell,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDot,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudLightning,
  CloudRain,
  CloudSun,
  CloudUpload,
  Cloudy,
  CornerUpLeft,
  Download,
  ExternalLink,
  FileText,
  Fingerprint,
  Flag,
  Hash,
  HelpCircle,
  History as HistoryIcon,
  Home,
  Image as ImageIcon,
  Images,
  Info,
  Layers,
  LayoutGrid,
  LogOut,
  MapPin,
  Minus,
  Pencil,
  Phone,
  PlayCircle,
  Plus,
  Printer,
  QrCode,
  Rocket,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Square,
  Sun,
  Tag,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
} from 'lucide-react-native';

type LucideCmp = React.ComponentType<{ size?: number; color?: string; style?: any; strokeWidth?: number }>;

// legacy name → lucide component
const ICON_MAP: Record<string, LucideCmp> = {
  add: Plus,
  remove: Minus,
  close: X,
  'close-circle': XCircle,
  checkmark: Check,
  'checkmark-done': CheckCheck,
  'checkmark-circle': CheckCircle2,
  'checkmark-circle-outline': CheckCircle,
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  'arrow-up-outline': ArrowUp,
  'arrow-down-outline': ArrowDown,
  'chevron-back': ChevronLeft,
  'chevron-forward': ChevronRight,
  'swap-horizontal-outline': ArrowLeftRight,
  'swap-vertical-outline': ArrowUpDown,
  'return-up-back-outline': CornerUpLeft,
  'home-outline': Home,
  'briefcase-outline': Briefcase,
  'people-outline': Users,
  'person-outline': User,
  'person-add-outline': UserPlus,
  'business-outline': Building2,
  'settings-outline': Settings,
  'document-outline': FileText,
  'document-text-outline': FileText,
  'clipboard-outline': ClipboardList,
  'bar-chart-outline': BarChart3,
  'trending-up-outline': TrendingUp,
  'cube-outline': Box,
  'archive-outline': Archive,
  'layers-outline': Layers,
  'grid-outline': LayoutGrid,
  'calendar-outline': Calendar,
  'time-outline': Clock,
  warning: AlertTriangle,
  'warning-outline': AlertTriangle,
  'alert-circle-outline': AlertCircle,
  'information-circle-outline': Info,
  'flag-outline': Flag,
  'shield-checkmark': ShieldCheck,
  'shield-checkmark-outline': ShieldCheck,
  'finger-print-outline': Fingerprint,
  location: MapPin,
  'location-outline': MapPin,
  'qr-code': QrCode,
  'qr-code-outline': QrCode,
  'pricetag-outline': Tag,
  'camera-outline': Camera,
  'image-outline': ImageIcon,
  'images-outline': Images,
  'download-outline': Download,
  'cloud-download-outline': CloudDownload,
  'cloud-upload-outline': CloudUpload,
  'open-outline': ExternalLink,
  'paper-plane-outline': Send,
  'play-circle-outline': PlayCircle,
  'print-outline': Printer,
  print: Printer,
  'search-outline': Search,
  'create-outline': Pencil,
  'trash-outline': Trash2,
  'keypad-outline': Hash,
  checkbox: CheckSquare,
  'square-outline': Square,
  'radio-button-on': CircleDot,
  'radio-button-off': Circle,
  'ellipse-outline': Circle,
  'sunny-outline': Sun,
  'partly-sunny-outline': CloudSun,
  'cloudy-outline': Cloudy,
  'cloud-outline': Cloud,
  'rainy-outline': CloudRain,
  'thunderstorm-outline': CloudLightning,
  'phone-portrait-outline': Smartphone,
  'call-outline': Phone,
  'log-out-outline': LogOut,
  'notifications-outline': Bell,
  'cash-outline': Banknote,
  'sparkles-outline': Sparkles,
  'rocket-outline': Rocket,
  history: HistoryIcon,
};

export type IconName = string;

export function Icon({
  name,
  size = 20,
  color = '#000',
  style,
}: {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}) {
  const Cmp = ICON_MAP[name] || HelpCircle;
  return <Cmp size={size} color={color} style={style} strokeWidth={2} />;
}

export default Icon;
